name: todoist-stats

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Todoist Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
