name: todoist-stats

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Todoist Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Updates to Todoist Stats"
          COMMIT_USERNAME: "gijinkakun"
          COMMIT_EMAIL: "gijinkakun@gmail.com"
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          GH_TOKEN: ${{ secrets.GIJINKAKUN_TOKEN }}
          PREMIUM: ""
