name: WakaTime Readme

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@6a37da63537fdc1cd0722c72c02c9f416f2cc7a6
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_TITLE: true
          SHOW_TOTAL: true


  

