name: wakatime-stats

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Updates to Wakatime Stats"
          COMMIT_USERNAME: "gijinkakun"
          COMMIT_EMAIL: "gijinkakun@gmail.com"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GIJINKAKUN_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"



